name: Add issues to projects

on:
  issues:
    types:
    - labeled
    - opened

jobs:
  add-to-qa-devops-project:
    name: Add issue to QA & DevOps project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/add-to-project@v0.3.0
      with:
        project-url: https://github.com/orgs/longhorn/projects/4
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labeled: kind/test, area/test-infra
        label-operator: OR

  add-to-community-project:
    name: Add issue to Community project
    runs-on: ubuntu-latest
    steps:
    - uses: JamesSingleton/is-organization-member@1.0.0
      id: is_organization_member
      if: github.event.action == 'opened'
      with:
        organization: longhorn
        username: ${{ github.event.issue.user.login }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/add-to-project@v0.3.0
      if: steps.is_organization_member.outputs.result == false
      with:
        project-url: https://github.com/orgs/longhorn/projects/5
        github-token: ${{ secrets.GITHUB_TOKEN }}
